In [1]:
import numpy as np
A =np.array([1,2,3,4])

In [2]:
Range = np.arange(10)

In [3]:
Range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
Srange = np.arange(0,10,2)

In [5]:
Srange

array([0, 2, 4, 6, 8])

In [6]:
E = np.eye(3,3)

In [7]:
E

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [9]:
L = np.linspace(1,100,10)

In [10]:
L

array([   1.,   12.,   23.,   34.,   45.,   56.,   67.,   78.,   89.,  100.])

In [11]:
N=np.arange(0,25)

In [12]:
N.shape

(25,)

In [14]:
N=N.reshape(5,5)

In [15]:
    N

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
S=np.ones(10)*5

In [17]:
S

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [19]:
D = np.random.randint(100,110,3)

In [20]:
D

array([100, 107, 108])

In [44]:
F=np.random.rand(3,10,4)

In [45]:
F

array([[[ 0.55096776,  0.89842622,  0.78848776,  0.98721117],
        [ 0.99798359,  0.77132732,  0.82652555,  0.22829852],
        [ 0.53538772,  0.40382544,  0.07845883,  0.67929997],
        [ 0.96257419,  0.50202013,  0.53937219,  0.92727017],
        [ 0.10904045,  0.53573167,  0.21912738,  0.25817229],
        [ 0.86862976,  0.16512938,  0.24753612,  0.52158227],
        [ 0.02380712,  0.64634089,  0.63429391,  0.17490583],
        [ 0.6559536 ,  0.53000495,  0.77272162,  0.81021887],
        [ 0.27089752,  0.67737082,  0.80311872,  0.99144563],
        [ 0.54468151,  0.49510435,  0.8194982 ,  0.24859827]],

       [[ 0.78562655,  0.07437347,  0.46529173,  0.91759972],
        [ 0.65181089,  0.69064879,  0.6791413 ,  0.71157593],
        [ 0.67375987,  0.63343821,  0.61561003,  0.75331203],
        [ 0.22322025,  0.06865096,  0.53119675,  0.70372929],
        [ 0.72801046,  0.97089819,  0.39457806,  0.03213646],
        [ 0.18474509,  0.74805451,  0.97786274,  0.31080883],
      

In [49]:
AA = np.arange(0,25).reshape(5,5)

In [50]:
AA

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
AA[2:5,2:4]

array([[12, 13],
       [17, 18],
       [22, 23]])

In [69]:
AA.sum(axis=0)

array([50, 55, 60, 65, 70])

In [53]:
AA[4,]

array([20, 21, 22, 23, 24])

In [54]:
NU = np.arange(10)

In [55]:
NU

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
NU[0:5] = 99

In [57]:
NU

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [59]:
CSU = NU.copy()

In [60]:
CSU

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [63]:
USC = np.array(CSU)

In [64]:
USC

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [65]:
SR=np.sqrt(USC)

In [66]:
SR

array([ 9.94987437,  9.94987437,  9.94987437,  9.94987437,  9.94987437,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [67]:
USC.sum()

530

In [68]:
USC.max()

99