In [1]:
import numpy as np
A =np.array([1,2,3,4])

In [2]:
Range = np.arange(10)

In [3]:
Range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
Srange = np.arange(0,10,2)

In [5]:
Srange

array([0, 2, 4, 6, 8])

In [6]:
E = np.eye(3,3)

In [7]:
E

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [9]:
L = np.linspace(1,100,10)

In [10]:
L

array([   1.,   12.,   23.,   34.,   45.,   56.,   67.,   78.,   89.,  100.])